### ISSUE TITLE
maybe the model par names change?

### ISSUE THREAD

**Issue by JiTao3** [dongyp13/Non-Targeted-Adversarial-Attacks#14]
```
Traceback (most recent call last):
  File "attack_iter.py", line 243, in <module>
    tf.app.run()
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "attack_iter.py", line 229, in main
    s1.restore(sess, FLAGS.checkpoint_path_inception_v3)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1755, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "InceptionV3/AuxLogits/Conv2d_2a_3x3/BatchNorm/beta" not found in checkpoint files inception_v3.ckpt
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op u'save/RestoreV2', defined at:
  File "attack_iter.py", line 243, in <module>
    tf.app.run()
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "attack_iter.py", line 219, in main
    s1 = tf.train.Saver(slim.get_model_variables(scope='InceptionV3'))
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1293, in __init__
    self.build()
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1302, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1339, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 796, in _build_internal
    restore_sequentially, reshape)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 449, in _AddRestoreOps
    restore_sequentially)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 847, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1030, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Tensor name "InceptionV3/AuxLogits/Conv2d_2a_3x3/BatchNorm/beta" not found in checkpoint files inception_v3.ckpt
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]


```

i get the  error above ,what should i do?

**Comment by Amarantine1** [comment]
> ```
> Traceback (most recent call last):
>   File "attack_iter.py", line 243, in <module>
>     tf.app.run()
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
>     _sys.exit(main(argv))
>   File "attack_iter.py", line 229, in main
>     s1.restore(sess, FLAGS.checkpoint_path_inception_v3)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1755, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
>     run_metadata_ptr)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1137, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
>     options, run_metadata)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "InceptionV3/AuxLogits/Conv2d_2a_3x3/BatchNorm/beta" not found in checkpoint files inception_v3.ckpt
>          [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> Caused by op u'save/RestoreV2', defined at:
>   File "attack_iter.py", line 243, in <module>
>     tf.app.run()
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
>     _sys.exit(main(argv))
>   File "attack_iter.py", line 219, in main
>     s1 = tf.train.Saver(slim.get_model_variables(scope='InceptionV3'))
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1293, in __init__
>     self.build()
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1302, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1339, in _build
>     build_save=build_save, build_restore=build_restore)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 796, in _build_internal
>     restore_sequentially, reshape)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 449, in _AddRestoreOps
>     restore_sequentially)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 847, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1030, in restore_v2
>     shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
>     op_def=op_def)
>   File "/home/jitao/anaconda3/envs/tf1/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> NotFoundError (see above for traceback): Tensor name "InceptionV3/AuxLogits/Conv2d_2a_3x3/BatchNorm/beta" not found in checkpoint files inception_v3.ckpt
>          [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> ```
> 
> i get the error above ,what should i do?

Hello, are you still studying this field? How is your reproduction of the author's method?
