### ISSUE TITLE
some problems about code

### ISSUE THREAD

**Issue by q4x3** [dongyp13/Non-Targeted-Adversarial-Attacks#18]
Sorry to interrupt. When I tried to run the code, it gives me the information below. Could you please tell me the probable reason for this? Thanks in advance.

> NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for inception_v3.ckpt
         [[Node: save/RestoreV2_142 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_142/tensor_names, save/RestoreV2_142/shape_and_slices)]]
         [[Node: save/RestoreV2_83/_639 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1708_save/RestoreV2_83", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by q4x3** [comment]
It seems that the program tried to read info from a file named "inception_v3.ckpt", which I didn't find in the folder... Is there any method to solve this problem?

**Comment by dongyp13** [comment]
You need to download the checkpoints at http://ml.cs.tsinghua.edu.cn/~yinpeng/nips17/nontargeted/models.zip.

**Comment by q4x3** [comment]
Thanks a lot for the ckpt files!! This time I run the program with those ckpt files, sadly there still exist some problems... Then it gives me the information below... It seems successfully read in the ckpt infos, however when reading in the png files it met with some encoding problems.. I guess it's the function scipy.misc.imread that result in this but I didn't find how to solve this..

> Traceback (most recent call last):
  File ".\attack_iter.py", line 244, in <module>
    tf.app.run()
  File "D:\software\conda\envs\tf_1_1\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File ".\attack_iter.py", line 239, in main
    for filenames, images in load_images(FLAGS.input_dir, batch_shape):
  File ".\attack_iter.py", line 93, in load_images
    image = imread(f, mode='RGB').astype(np.float) / 255.0
  File "D:\software\conda\envs\tf_1_1\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "D:\software\conda\envs\tf_1_1\lib\site-packages\scipy\misc\pilutil.py", line 164, in imread
    im = Image.open(name)
  File "D:\software\conda\envs\tf_1_1\lib\site-packages\PIL\Image.py", line 2887, in open
    prefix = fp.read(16)
  File "D:\software\conda\envs\tf_1_1\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 122, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "D:\software\conda\envs\tf_1_1\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 90, in _prepare_value
    return compat.as_str_any(val)
  File "D:\software\conda\envs\tf_1_1\lib\site-packages\tensorflow\python\util\compat.py", line 106, in as_str_any
    return as_str(value)
  File "D:\software\conda\envs\tf_1_1\lib\site-packages\tensorflow\python\util\compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by dongyp13** [comment]
I'm not sure about this problem, maybe due to the scipy.misc versions. I suggest to try other image loading functions, such as PIL.Image, which may be more stable.

**Comment by q4x3** [comment]
I tried PIL.Image, which gives me same error information. Then I tried to rewrite the code in the readin part, and it worked well. It seems that in your code, type of f makes f unable to be accepted as parameter of  imread (or Image.open)(in attack_iter.py, line 92). (However, it seems weird that imsave works fine)
